use_frameworks!

platform :ios, '15.6'

target 'ZLUtilities_Example' do
  pod 'ZLUtilities', :path => '../'

  target 'ZLUtilities_Tests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end
